/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import javax.swing.Timer;

/**
 *
 * @author nschu
 */
public class Ventana extends javax.swing.JFrame {
private Timer tiempo;
private int centesimas =0 , segundos=0 , minutos=0, horas=0;
private ActionListener acciones = new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        centesimas++;
        if(centesimas==100){
            segundos++;
            centesimas=0;
            
        }
        if (segundos==60){
            minutos++;
           segundos=0;
        }
        if(minutos==60){
            horas++;
            minutos=0;
        }
           
        actulizarEtiqueta();

    }

    
};

private void actulizarEtiqueta() {
       String texto = (horas<=9?"0":"")+horas+" : "+(minutos<=9?"0":"")+
               minutos+" : "+(segundos<=9?"0":"")+segundos+" : "+(centesimas<=9?"0":"")+centesimas;
       Tiempo.setText(texto);
}


public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        Cronometro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        pausar = new javax.swing.JButton();
        detener = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cronometro1.png"))); // NOI18N
        panel.add(Cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 210));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cronometro");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 260, 70));

        Tiempo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        Tiempo.setForeground(new java.awt.Color(255, 255, 255));
        Tiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tiempo.setText("00: 00: 00");
        panel.add(Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 240, 50));

        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        panel.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 70, 30));

        pausar.setText("Pausar");
        pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarActionPerformed(evt);
            }
        });
        panel.add(pausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 80, 30));

        detener.setText("Detener");
        detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerActionPerformed(evt);
            }
        });
        panel.add(detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 80, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/fondo (1).jpg"))); // NOI18N
        panel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 600, 600));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/fondo (1).jpg"))); // NOI18N
        panel.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarActionPerformed
        tiempo.stop();
        iniciar.setEnabled(true);
    }//GEN-LAST:event_pausarActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        tiempo.start();
        iniciar.setEnabled(false);
        iniciar.setText("Reanaudar");
        pausar.setEnabled(true);
        detener.setEnabled(true);
    }//GEN-LAST:event_iniciarActionPerformed

    private void detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerActionPerformed
        if(tiempo.isRunning()){
            tiempo.stop();
            iniciar.setEnabled(true);
            
        }
        iniciar.setText("Iniciar");
        pausar.setEnabled(false);
        detener.setEnabled(false);
        
        horas=0;
        segundos=0;
        centesimas=0;
        minutos=0;
        
        this.actulizarEtiqueta();
        
    }//GEN-LAST:event_detenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cronometro;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JButton detener;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton pausar;
    // End of variables declaration//GEN-END:variables
}
